name: Build Go Binary

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

      - name: Build Binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          BINARY_NAME="recycleapp-ics"
          if [ "${{ matrix.goos }}" = "windows" ]; then
            BINARY_NAME="recycleapp-ics.exe"
          fi
          go build -v -o "dist/${BINARY_NAME}-${{ matrix.goos }}-${{ matrix.goarch }}" .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: recycleapp-ics-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/*
